cmd/doctree: Add automatic re-indexing
sourcegraph/doctree pull request #28
Opened 2022-05-12 11:00 UTC by KShivendu

- [x] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received 
permission to do so by an employer or client I am producing work for whom has this right.

2022-05-12 19:19 UTC, KShivendu commented
Here's how automatic re-indexing works at the moment:

- User registers the project using `doctree add .`
- Store the project metadata in `~/.doctree/autoindex` in the format: `[{projectName: ..., path: ..., hash: ...}]`
- Calculate the hash using the command `tar -cf - directory | md5sum`

Whenever the user stars the server using `doctree serve`. The following happens:
- Start the HTTP server as expected
- Recompute hashes of all the registered projects and reindex if the hash has changed. (because changes can happen when the server was down)
- Initialize a `fsnotify.watcher` and register all the dirs mentioned in `~/.doctree/autoindex` along with their nested dirs (excluding hidden dirs)
- If the watcher says that a file has been altered, find its corresponding project and re-index the project. 

I haven't implemented partial re-indexing in this PR. I'm planning to cover it in another PR. Please review this one and suggest changes wherever required. 

Please note that Go isn't my first language. So I'm not aware of all the best practices and might have made some mistakes. So please be careful with the review :)

2022-05-12 20:31 UTC, slimsag commented on doctree/schema/schema.go
> +type AutoIndexedProject struct {
We should put this type somewhere else, maybe in `doctree/indexer/indexer.go` for example.

The idea with `schema.go` is that it describes the schema an _indexer_ would emit, this is more of an internal concept / not related to what an indexer would output so we should put it somewhere else.

2022-05-12 20:42 UTC, slimsag commented on doctree/indexer/python/indexer.go
> +		content, err := ioutil.ReadFile(dir + "/" + path)
`filepath.Join(dir, path)` is generally better style in Go (it prevents a whole slew of accidental cases you might run into, like if one side is an empty string - or duplicate slashes, or handling Windows slash style)

But I think it would be better if this logic stayed in the loop that produces `sources` - the idea being that loop finds sources, this one just consumes them. What was the motivation for this change?

2022-05-12 20:44 UTC, slimsag commented on doctree/indexer/python/indexer.go
> +		content, err := ioutil.ReadFile(dir + "/" + path)
Oh! I think I know the problem, we're using `ioutil.ReadFile(path)` here, but `path` is relative to a VFS so you had to add the dir in.

I think if we use:

```Go
dirFS := os.DirFS(dir)
content, err := fs.ReadFile(dirFS, path
```

That should probably do the trick!

2022-05-12 20:48 UTC, slimsag commented on cmd/doctree/util.go
> +	tarCmd := exec.Command("tar", "-cf", "-", dir)
May be OK for now, but we'll need to come up with something smarter than this I think. I'm not totally sure I follow the needed for a directory hash, maybe you can explain the idea behind that a bit more for me?

The problem with this is:

1. `tar` isn't available on Windows, might not be available in Docker images, etc. Not nice to depend on an external tool in general
2. It can be quite slow - I have a large project that this takes almost a minute to complete on:

```
$ time sh -c 'tar -cf - . | md5sum'
cd434e78961999ed1a7e56cfcd29cdf7  -

real	0m57.865s
user	0m14.312s
sys	0m24.263s
```

May be good enough for now, though! Happy to land this as-is and revisit the idea later.

2022-05-12 20:55 UTC, slimsag commented on cmd/doctree/serve.go
> +		go Serve(*cloudModeFlag, *httpFlag, indexDataDir)
I think it would be better if these read like:

```go
go log.Fatal(ListenAutoIndexedProjects(dataDirFlag))
```

Then each function can just return an error value if it is fatal, or use `log` otherwise if not fatal.

2022-05-12 20:56 UTC, slimsag commented on cmd/doctree/serve.go
> +		log.Fatal(err)
Replace these with `return errors.Wrap(err, "ReadAutoIndex")` so we know where the error came from (otherwise you can maybe get a vague error like `unexpected character ' when decoding JSON` without knowing what it was trying to decode :)

2022-05-12 21:02 UTC, slimsag commented on cmd/doctree/serve.go
> +		if GetDirHash(project.Path) != project.Hash {
If I understand correctly, the primary purpose of dir hash is to check if directory has changed while the server was not running. If yes, let's leave this as-is for this PR and improve later.

2022-05-12 21:03 UTC, slimsag commented on cmd/doctree/index.go
> +func RunIndexers(ctx context.Context, dir string, dataDirFlag, projectFlag *string) error {
Could maybe move to the `indexer` package.

2022-05-12 21:05 UTC, slimsag commented on cmd/doctree/add.go
> +func WriteAutoIndex(path string, autoindexedProjects []schema.AutoIndexedProject) error {
Let's move these to `indexer` package too. Maybe in a `cli.go` file.

Idea being: `cmd/doctree` code should just be a lightweight thing that calls into `indexer` package, so that if you wanted to use it in a non-CLI context it'd be easy to do so.

2022-05-12 21:06 UTC, slimsag requested changes
This looks really great, thanks for working on this! I'm very excited to have this functionality :D 

I left some suggestions & questions inline, but looks great to me otherwise!

2022-05-13 20:47 UTC, KShivendu commented on cmd/doctree/add.go
> +func WriteAutoIndex(path string, autoindexedProjects []schema.AutoIndexedProject) error {
Done.

2022-05-13 20:47 UTC, KShivendu commented on cmd/doctree/index.go
> +func RunIndexers(ctx context.Context, dir string, dataDirFlag, projectFlag *string) error {
Done.

2022-05-13 20:47 UTC, KShivendu commented on cmd/doctree/serve.go
> +		if GetDirHash(project.Path) != project.Hash {
Okay. Removing the hashing part.

2022-05-13 20:47 UTC, KShivendu commented on cmd/doctree/serve.go
> +		log.Fatal(err)
Done. Thanks!

2022-05-13 20:47 UTC, KShivendu commented on cmd/doctree/serve.go
> +		go Serve(*cloudModeFlag, *httpFlag, indexDataDir)
Thanks! This was much cleaner.

But looks like it blocks the process. I couldn't exit using Ctrl+C so I tried the following:

```go
go Serve(*cloudModeFlag, *httpFlag, indexDataDir)
go func() {
	err := ListenAutoIndexedProjects(dataDirFlag)
	if err != nil {
		log.Fatal(err)
	}
}()
<-signals
```

and it worked.

2022-05-13 20:47 UTC, KShivendu commented on doctree/indexer/python/indexer.go
> +		content, err := ioutil.ReadFile(dir + "/" + path)
Thanks!

2022-05-13 20:47 UTC, KShivendu commented on doctree/schema/schema.go
> +type AutoIndexedProject struct {
Makes sense. Done.

2022-05-13 20:47 UTC, KShivendu commented
Apart from your suggestions, I also did the following:
1. Set `projectFlag` based on the value of `dir`. (Previously it always stored the URL of the current directory irrespective of the `dir` value)
2. Use map instead of arrays in `~/.doctree/autoindex` to avoid adding the same dir (project) multiple times. 
Before: `[{"name": "github.com/user/repo", "path": "/path/to/project"}]`
After: `{"/path/to/project": {"name": "github.com/user/repo"}}`
3. `doctree/indexer/cli.go`: Create `~/.doctree/autoindex` if it doesn't exist when running `doctree serve` (I feel that its code could be cleaner. Would really appreciate if you could give suggestions to improve it)

2022-05-13 20:49 UTC, KShivendu commented on cmd/doctree/add.go
> +		}
Point 1 of https://github.com/sourcegraph/doctree/pull/28#issuecomment-1126489302

> Set projectFlag based on the value of dir. (Previously it always stored the URL of the current directory irrespective of the dir value)

2022-05-13 20:49 UTC, KShivendu commented on cmd/doctree/index.go
> +			*projectFlag = defaultProjectName(dir)
Point 1 of https://github.com/sourcegraph/doctree/pull/28#issuecomment-1126489302

> Set projectFlag based on the value of dir. (Previously it always stored the URL of the current directory irrespective of the dir value)

2022-05-13 20:50 UTC, KShivendu commented on doctree/indexer/indexer.go
> +}
See point 3 of https://github.com/sourcegraph/doctree/pull/28#issuecomment-1126489302

> Use map instead of arrays in ~/.doctree/autoindex to avoid adding the same dir (project) multiple times.
Before: [{"name": "github.com/user/repo", "path": "/path/to/project"}]
After: {"/path/to/project": {"name": "github.com/user/repo"}}

2022-05-13 20:51 UTC, KShivendu commented on doctree/indexer/cli.go
> +	err = json.Unmarshal(data, &autoIndexedProjects)
See point 3 of https://github.com/sourcegraph/doctree/pull/28#issuecomment-1126489302

> Create ~/.doctree/autoindex if it doesn't exist when running doctree serve (I feel that its code could be cleaner. Would really appreciate if you could give suggestions to improve it)

2022-05-13 20:53 UTC, KShivendu commented on cmd/doctree/util.go
> +	tarCmd := exec.Command("tar", "-cf", "-", dir)
I agree. Will try to look for something better than this.

2022-05-16 08:51 UTC, keegancsmith commented on cmd/doctree/util.go
> +	tarCmd := exec.Command("tar", "-cf", "-", dir)
additionally I'm unsure if it is required for tar to have deterministic output, ie does it sort directory entries before adding them? It may just rely on the order of readdir which can change even if the underlying files have not changed.

2022-05-17 02:30 UTC, slimsag commented
Nice work! I've added an `EXPERIMENTAL` warning to the helper menu while we sort out the remaining issues here, but otherwise looks like a great starting point for this functionality & happy to merge this as-is! Thanks for doing this :)

---

Some notes for myself to follow up on later:

* macOS: I had to run `ulimit -n 10000`, or else I'd get `bad file descriptor` errors.
* On Linux we may need to suggest [something like this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@98f2dfad8fe63e080e1b91b28e58bf9b885d48cb/-/blob/doc/dev/setup/troubleshooting.md?L48-55)
* Probably should query for the above at runtime, then suggest the user run those commands if needed. May be able to steal code for this from the `sg` tool.
* Apparently fsevents on macOS is nicer than fsnotify: https://github.com/fsnotify/fsnotify/issues/8 https://github.com/fsnotify/fsnotify/issues/11 - I should look into integrating this for macOS maybe.
* Will need to fix the tar issue.
* Need to add a "settle" period for event handling, when ran in a project that has had a ton of changes it can end up reindexing quite a lot.
* Need to sort out how to ignore `.git`, `node_modules`, etc. events (and exclude those from doc generation/indexing in general!)

2022-05-17 02:30 UTC, merged